// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd6nRgxR5ZTfDz9FTqKoaHATKwqWoHJPg',
    appId: '1:382620787937:web:7a6d1d222546b561a943a0',
    messagingSenderId: '382620787937',
    projectId: 'chatapp-9ca09',
    authDomain: 'chatapp-9ca09.firebaseapp.com',
    storageBucket: 'chatapp-9ca09.appspot.com',
    measurementId: 'G-0M9REPSDDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG1bplMfa-s2EgnxbDBp9vMk7lfzonX-Q',
    appId: '1:382620787937:android:887028078e28e10ba943a0',
    messagingSenderId: '382620787937',
    projectId: 'chatapp-9ca09',
    storageBucket: 'chatapp-9ca09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW8a7ETg_Zb1Ub2yajtwHY47x5rpDVW94',
    appId: '1:382620787937:ios:bd61d7600334d5d1a943a0',
    messagingSenderId: '382620787937',
    projectId: 'chatapp-9ca09',
    storageBucket: 'chatapp-9ca09.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW8a7ETg_Zb1Ub2yajtwHY47x5rpDVW94',
    appId: '1:382620787937:ios:bd61d7600334d5d1a943a0',
    messagingSenderId: '382620787937',
    projectId: 'chatapp-9ca09',
    storageBucket: 'chatapp-9ca09.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd6nRgxR5ZTfDz9FTqKoaHATKwqWoHJPg',
    appId: '1:382620787937:web:c1334bbc86f73f9aa943a0',
    messagingSenderId: '382620787937',
    projectId: 'chatapp-9ca09',
    authDomain: 'chatapp-9ca09.firebaseapp.com',
    storageBucket: 'chatapp-9ca09.appspot.com',
    measurementId: 'G-1G8PJRN1W1',
  );

}